workspace 'VLNRABLE'
platform :ios, '7.0'
xcodeproj 'VLNRABLE/VLNRABLE.xcodeproj'

pod 'AFNetworking'
pod 'CocoaLumberjack'
pod 'GoogleAnalytics-iOS-SDK'
pod 'GoogleTagManager'
pod 'Kiwi'
pod 'M13Checkbox'
pod 'MZFormSheetController'
pod 'NewRelicAgent'
pod 'Nocilla'
pod 'Reachability'
pod 'SDWebImage'
pod 'SDWebImage-ProgressView'
pod 'SVProgressHUD'
pod 'TestFlightFeedback'
pod 'TestFlightLogger'
pod 'TestFlightSDK'
